version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - API_ORIGIN=${API_ORIGIN:-http://localhost:5100}
      - VIEWER_URL=${VIEWER_URL:-http://host.docker.internal:9090/essential_viewer}
      - VIEWER_USER=${VIEWER_USER:-alice}
      - VIEWER_PWD=${VIEWER_PWD:-s3cr3t}
    # To allow connecting to localhost services from inside the container on Linux/Mac
    extra_hosts:
      - "host.docker.internal:host-gateway"
